# Generated by Django 3.2 on 2021-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0011_auto_20210528_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('mensaje', models.TextField(default='--')),
            ],
        ),
    ]
