# Generated by Django 3.2 on 2021-05-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0012_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
